# Generated by Django 5.0.6 on 2024-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='profesion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
