# Generated by Django 5.0.6 on 2024-07-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_estudiante_profesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Historia',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Redes',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
