# Generated by Django 5.0.6 on 2024-08-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0007_alter_productos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
